apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170593684
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170593684
    app.kubernetes.io/part-of: test-app-170593684
  name: java-quarkus-170593684
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170593684
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170593684
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/user1-tenant/test-app-170593684/java-quarkus-170593684@sha256:bbc6a32e16ec0d27cfca8de9fa90df3cb51ae297ad1c2b06c1e3509189b8568c
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
